#spring.datasource.url= jdbc:mysql://localhost:3306/mydatabase
#spring.datasource.username: root
#spring.datasource.password: Temp1234
#spring.jpa.hibernate.ddl-auto= create

server:
  port: 8282
spring:
  datasource:
    password: Temp1234
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
  jpa:
    hibernate:
      ddl-auto: create
      
    show-sql: true
    properties:
      hibernate:
      format_sql: true