server:
  port: 8484
spring:
  datasource:
    password: Temp1234
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      format-sql: true
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        exclude:
        - health
        - beans
      base-path: /myactuator
 